module.exports = {
  MR: "Mr.",
  expiresIn: "2h",
  dateNow: Date.now,
  limit : 10,
  path: {
    CSS: "/public/css",
    admin: "/static/admin/",
    merchant: "/static/merchant/",
    category : "/static/category/",
    product : "/static/product/",
    addOns : "/static/addons/",
    subCategory : "/static/subcategory/",
    user: "/static/users/", 
    adminUploads: "uploads/admin",
    userUploads: "uploads/users",
    merchantUploads: "uploads/merchant",
    categoryUploads: "uploads/category",
    subCategoryUploads: "uploads/subcategory",
    productUploads: "uploads/product",
    addOnsUploads: "uploads/addons",
    pdfFiles :"/static/invoices/",
    pdfUploads :"/invoices",
  },
};
