module.exports = {
  alreadyExists: "User with same email or username already exists",
  registeredSuccessfully: "succesfully registered",
  internalServerError: "Internal Server Errror",
  successfullyInsertedDatas: "Successfully inserted Datas",
  userNotFound: "User not found",
  usersFound: "Users Found",
  SUCCESS: "SUCCESS",
  BAD_REQUEST: "BAD REQUEST",
  UNAUTHORIZED_ACCESS: "UNAUTHOROIZED ACCESS",
  ACCESS_FORBIDDEN: "ACCESS FORBIDDEN",
  FETCHED_SUCCESSFULLY: "Fetched Successfully",
  passwordIncorrect: "username or password incorrect",
  uploadOneImageSuccessfully: "you have uploaded One image ",
  uploadedManyImagesSuccessfully: "you have uploaded following images ",
  uploadedImageFieldSuccessfully: "uploaded Fields Successfully",
  active: "is Active",
  deativatedSuccessfully: "is deactivated",
  activatedSuccessfully: "successfully activated",
  deactivatedSuccessfully: "successfully deactivated",
  deletedSuccessfully: "You Deleted ",
  deletedSuccessFully: "deleted Successfully",
  blockedSuccessfully: " blocked successfully",
  unblockedSuccessfully: "Unblocked successsfully",
  welcome: "WELCOME ",
  incorrectEmailString: "Incorrect Email String",
  verifiedSuceessfully: "you have successfully verified your account",
  emailNotVerified: "Your Email is not verified",
  phoneNotVerified: "Your Phone is not verified",
  accountNotVerified: "Your account is not verified",
  invalidOTP: "Invalid OTP",
  blockedByAdmin: "You are blocked by the admin",
  provideDetails: "provide your ",
  checkEmail: "please check your email to reset password",
  tokenExpired: "your token is expired",
  somethingWentWrong: "something went wrong",
  passwordChangedSuccessfully: "Password Changed successfully",
  passwordAndNewPasswordNotSame: "password and confirm password are not same",
  phone: "phone",
  email: "email",
  forgetPassword: "forgetPassword",
  verfyPhone: "verifyPhone",
  verifyEmail: "verifyEmail",
  resendOTP: "resendOTPForVerification",
  CheckYour: "To reset password Check Your",
  SUCCESS: "SUCCESS",
  CHECK_YOUR_OTP: "Please Check your OTP on ",
  ONLY_IMAGE_FILES: "Only .jpg .png or .jpeg format allowed",
  OTP: "Your OTP for Expandimo is",
  RESET_OTP: "Your Reset OTP for Expandimo is",
  RESEND_OTP: "Your resent OTP for Expandimo is",
  NO_DATA: "No data found",
  NO_SUB_CATEGORY: "No Subcategory found",
  SUBCATEGORY_ALREADY_EXISTS: "Subcategory already exists",
  NO_CATEGORY: "No Category found",
  CATEGORY_ALREADY_EXISTS: "category already exists",
  DEFAULT_BODY: "default body",
  NO_ADDRESS_FOUND: "NO ADDRESS FOUND",
  ADDRESS_ALREADY_EXISTS : "ADDRESS ALREADY EXISTS", 
  ACCOUNT_CREDENTIAL: "sendCredential",
  NO_PRODUCT_FOUND: "NO  PRODUCTS FOUND",
  PRODUCT_ALREADY_EXISTS: "Product Already exists",
  MERCHANT_NOT_FOUND: "MERCHANT NOT FOUND",
  MERCHANT_ALREADY_EXISTS: "MERCHANT_ALREADY_EXISTS",
  objectIdInvalid: "OBJECT_ID_INVALID",
  SUCCESFULLY_RECOVERED: "SUCCESFULLY_RECOVERED_DATA",
  CHARGES_ALREADY_EXISTS: "CHARGES_ALREADY_EXISTS",
  NO_CHARGES_FOUND: "NO_CHARGES_FOUND",
  NO_CART_FOUND : "NO CART FOUND",
  ITEM_NOT_FOUND_IN_CART : "ITEM NOT FOUND IN CART",
  NO_ADDONS_FOUND : "NO_ADDONS_FOUND",
  ADDONS_ALREADY_EXISTS :  "ADDONS_ALREADY_EXISTS",
  SUCCESFULLY_PLACED_ORDER : "PLACED ORDER SUCCESFULLY",
  CLEARED_CART_SUCCESSFULLY : "CLEARED CART SUCCESSFULLY" ,
  NO_ORDER_FOUND : "NO ORDER FOUND",
  ROOM_ALREADY_EXISTS : "YOU HAVE A ROOM ALREADY WITH SAME NAME",
  NOT_A_MEMBER : "YOU ARE NOT A MEMBER OF THIS GROUP",
  ALREADY_EXISTS : "ALREADY EXISTS"
};
